### Send POST request with body as parameters
POST http://127.0.0.1:8881/server/sendByToken
Content-Type: application/x-www-form-urlencoded

token=100&body=content


###

# curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
POST http://120.46.210.11:8848/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080

###

### 远程参数下发读取
POST http://127.0.0.1:8881/server/admin/electronicLock?pileCode=471000220714302005&command=open

### 远程参数下发读取
POST http://127.0.0.1:8881/server/electronic/close?pileCode=471000220714302005

### 远程参数下发读取
POST http://127.0.0.1:8881/server/admin/reboot?pileCode=471000220714302005

### 远程参数下发读取
POST http://127.0.0.1:8881/server/admin/lock?pileCode=471000220714302005&command=unlock



### 远程参数下发读取
POST http://127.0.0.1:8881/server/setParameter
Content-Type: application/x-www-form-urlencoded

idCode=471000220714302005

### 启动充电
POST http://127.0.0.1:8881/server/startCharge?idCode=471000220714302005
Content-Type: application/x-www-form-urlencoded

### 启动充电
POST http://127.0.0.1:8881/server/endCharge
Content-Type: application/x-www-form-urlencoded

idCode=471000220822302003&orderNumber=80edb1708a4944afbd3949d90fad6703


### 命令转义
POST http://127.0.0.1:8881/codec/transferEncode
Content-Type: application/x-www-form-urlencoded

body=23 31 01 0A 00 9B 05 34 37 31 30 30 30 32 32 30 37 31 34 33 30 32 30 30 35 23 08 17 16 57 54 FF FF FF FF 89 23